-- ======= DO NOT EDIT THIS FILE ======= --

if TLS.Fleece.Enable then
    RegisterCommand(TLS.Fleece.Command, function()
        local playerPed = PlayerPedId()
        local currentGender, currentFleece, currentTexture = TLS.Functions.GetPlayerGender(playerPed), TLS.Functions.GetPlayerDrawable(playerPed, 11, false)
        for k, v in ipairs(TLS.Fleece[currentGender]) do
            if v.mainComponent == currentFleece then
                RequestAnimDict('clothingtie')
                while not HasAnimDictLoaded('clothingtie') do
                    Wait(10)
                end
                TaskPlayAnim(playerPed, 'clothingtie', 'try_tie_positive_a', 3.0, 3.0, -1, 49, 0, 0, 0, 0)
                Wait(2500)
                SetPedComponentVariation(playerPed, 11, v.newComponent, currentTexture, 0)
                Wait(2000)
                ClearPedTasks(playerPed)
                RemoveAnimDict('clothingtie')
                break
            end
        end
    end, false)
    
    RegisterKeyMapping(TLS.Fleece.Command, TLS.Fleece.Label, 'keyboard', TLS.Fleece.Keybind)
end
